### ISSUE TITLE
Suggestions for better default hotkeys?

### ISSUE THREAD

**Issue by Vegz78** [Vegz78/retro2png#2]
If you have any good suggestions for better default hotkeys/hotkey combinations than `r+2+p` on the keyboard and `Mode/PS+DPAD_UP` on a PS3/XBox controller type(more buttons), please post below.

I have received some feedbacks that `r+2+p` is unnecessary cumbersome and that `Mode/PS+DPAD_UP` doesn't work on e.g. most 8 bit gamepads(missing Mode/PS button).

The challenge is that many single key hotkeys/shortcuts(how about F8?) on the keyboard already are taken by other popular apps/functions and most, if not all, button combinations on 8 bit gamepads are already reserved in RetroPie and other game frontends/launchers:
https://github.com/RetroPie/RetroPie-Setup/wiki/Controller-Configuration#hotkeys

**Comment by bverc** [comment]
For keyboard, I suggest F12, which is what Steam uses. You should also avoid using keys from this list:
https://retropie.org.uk/docs/Keyboard-Controllers/

For controllers, you raise a good point. Not all have a MODE button however. SELECT + UP might be a better combination, but that will still interfere with some games.
