### ISSUE TITLE
failed to open vchiq instance

### ISSUE THREAD

**Issue by 2play** [Vegz78/retro2png#3]
Tested installation on a Tinker and RockPro64 boards (RK3288 & RK3399)
but I get above when run it
"failed to open vchiq instance"
pi user already in the video group :-)
Any idea?

**Comment by Vegz78** [comment]
Hi @2play,

Sorry for my late reply.

It’s been a while now since I have used and tinkered with my version of AndresFromMelbourne’s raspi2png.

The Broadcom-specific Dispmanx graphics API used has long been due for deprecation on Raspberry Pi OS(RPiOS), and I am not aware anymore of the continued support in newer RPiOS releases or on newer RPi boards. Do the Tinker and RockPro64 have similar bcm graphics chips?

I could of course one day test retro2png on an updated RPiOS distribution on my newest RPi4, to see if it still works, if this could be of any help to you? Though I am not familiar with your boards, nor if such a test would be of any relevance to them?

**Comment by 2play** [comment]
Hi @Vegz78 First of all thank you for your reply and kind effort to help 
Raspi2png is working on all pi I tested 0,3,4
There is another tool that does to jpg (ill send you link) but all 3 are based on bcm_host and opt/vc libs
The Asus TinkerBoard and Pine64 Rockpro64 are based on Rockchip arm soc. Asus has their source code open on their got of that can help

In the mean time I made a script that choses automatically scrot or fbgrab to make screenshot depending if console or x11 is running 
But none can take screen grab when for example emulationstation or a graphical app is running without X
I tried kmsgrab but no success yet.
I cant find a universal tool to do screen dump/shot over ssh as I can do with yours/raspi2png/screenshot tool(jpg)

Any ideas are always welcome!

**Comment by Vegz78** [comment]
> Raspi2png is working on all pi I tested 0,3,4 

Thanks for confirming that it still seems to work on newer RPis and RPiOS distros!


> There is another tool that does to jpg (ill send you link) but all 3 are based on bcm_host and opt/vc libs 

Yeah, I briefly discovered another fork of raspi2png(raspi2jpg?) when I was working on this, which saved directly to jpeg images using the same Dismanx capture, if that's the one you are thinking about?

> The Asus TinkerBoard and Pine64 Rockpro64 are based on Rockchip arm soc. Asus has their source code open on their got of that can help

Are you here confirming my suspicion that the Dispmanx API used for screen capture in raspi2png on the RPi wouldn't work on the Rockchip?

> In the mean time I made a script that choses automatically scrot or fbgrab to make screenshot depending if console or x11 is running But none can take screen grab when for example emulationstation or a graphical app is running without X I tried kmsgrab but no success yet. I cant find a universal tool to do screen dump/shot over ssh as I can do with yours/raspi2png/screenshot tool(jpg)

Are you sure that _fbgrab_ does not do what you seek with the right options specified? According to their website:
"_You can use it for  making  screenshots  of  of
   virtually  any  application, from traditional test applications to your
   X-windows desktop, as well as framebuffer applications_"
https://github.com/GunnarMonell/fbgrab#description 
 
> Any ideas are always welcome!

I am sorry, I ended up with the retro2png project after an extensive search for alternatives, with almost the same requirements specification as you. In addition to dumping any screen content on my RPi from ssh, I wanted some HID key/button combination shortcut and an automatic sequence of file names, primarily to dump from retro games in RetroPie, Blast16, Recalbox etc. I found the easiest for me was to link retro2png with triggerhappy for shortcuts and some light modification of the source code for automatic file name sequencing.

Apart from _fbgrab_, the screendump functionality inside RetroPie and Recalbox, and the others you mentioned, I don't know, sorry.

**Comment by 2play** [comment]
I'll have a look at fbgrab again. Scrot is great for x11 via ssh or not.  
Fbgrab great from anything text based on console.
As you also I needed to make screenshot of my themes on es or gameplay etc
Here is the other tool that I was using mainly also work on pi4
https://github.com/info-beamer/tools/tree/master/screenshot
Uses same library bcm host 
That is  where compiling fails.
And he plainly told me he isn't interested to do any work apart pi.
Asus tinker code https://github.com/TinkerBoard
I hoped ffmpeg kmsgrab would do the magic but no luck there

**Comment by Vegz78** [comment]
Did you find a working solution eventually?

**Comment by 2play** [comment]
@Vegz78 unfo not yet. I ve been tesing fbgrab extra device option but i get errors. it does nicely the framebuffer but for x11 from ssh i use scrot.
My script works great to pick the enviroment and run appropriate grubber but I need to manage yet to get the screenshot of the console running an app as ES
ill keep testing the fbgrab and/or kmsgrab

**Comment by Vegz78** [comment]
Good luck!

Would be great to hear about your final findings! -There are many use cases I can think of for this outside of the RPi and when Dispmanx is discontinued.

Mvh,

Vegard

6. mai 2022 kl. 11:49 skrev 2play ***@***.***>:

﻿

@Vegz78<https://github.com/Vegz78> unfo not yet. I ve been tesing fbgrab extra device option but i get errors. it does nicely the framebuffer but for x11 from ssh i use scrot.
My script works great to pick the enviroment and run appropriate grubber but I need to manage yet to get the screenshot of the console running an app as ES
ill keep testing the fbgrab and/or kmsgrab

**Comment by 2play** [comment]
@Vegz78 I will my friend! Again thank you for taking the time to chat with me

**Comment by Vegz78** [comment]
@2play, did or how did you conclude on this matter?

**Comment by 2play** [comment]
@Vegz78 sorry for the delay. Im away till 27th June. But if i can ill reply to you earlier with a new solution! works on all

**Comment by 2play** [comment]
@Vegz78 good day my friend! tx for your patience. I got back to the office and got hectic but i had you in my mind to reply
all you need to do is to compile this and put binary to your path.
It compiles in secs and does all 3 things we need over ssh or not (x11, kms, framebuffer) to png.
for me i took it a step further to make jpg for my needs.
but for png it does all and no library specific requirements

**Comment by Vegz78** [comment]
Hi @2play,

Nice to hear back from you with a feedback about you having found a working solution!

But sorry for not fully recollecting the full picture. 

Did retro2png or a raspi2png fork which you have modified to give jpg support finally compile directly and work with the above mentioned x11, kms and framebuffer on The Asus TinkerBoard and Pine64 Rockpro64?

**Comment by 2play** [comment]
> Hi @2play,
> 
> Nice to hear back from you with a feedback about you having found a working solution!
> 
> But sorry for not fully recollecting the full picture.
> 
> Did retro2png or a raspi2png fork which you have modified to give jpg support finally compile directly and work with the above mentioned x11, kms and framebuffer on The Asus TinkerBoard and Pine64 Rockpro64?

My apologies for the mix up. I forgot to send you the link to the code. 
No the rapsi2png not working as its depended on the  bcm library therefore only for pi. And since no dev helped me I found a new solution which I further adjusted to my need and works on all boards I needed Tinker, Rockpro64 and should work on pi2 as I plan to replace my old setup 
https://github.com/pcercuei/kmsgrab
This is what you need to compile and add to your path.
Let me know!

**Comment by Vegz78** [comment]
Thanks for the link! Great replacement you have found for other boards and when RPi abandons Dispmanx.
